# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/chat',
                'doc_host': 'https://northarray.github.io',
                'git_url': 'https://github.com/northarray/chat',
                'lib_path': 'chat'},
  'syms': {'chat.core': {'chat.core.foo': ('core.html#foo', 'chat/core.py')}}}
