# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/chat',
                'doc_host': 'https://northarray.github.io',
                'git_url': 'https://github.com/northarray/chat',
                'lib_path': 'chat'},
  'syms': { 'chat.chat': { 'chat.chat.MsgType': ('chat.html#msgtype', 'chat/chat.py'),
                           'chat.chat.ask_llm': ('chat.html#ask_llm', 'chat/chat.py'),
                           'chat.chat.bubble': ('chat.html#bubble', 'chat/chat.py'),
                           'chat.chat.chatpg': ('chat.html#chatpg', 'chat/chat.py'),
                           'chat.chat.llm_rsp': ('chat.html#llm_rsp', 'chat/chat.py'),
                           'chat.chat.mk_prompt': ('chat.html#mk_prompt', 'chat/chat.py'),
                           'chat.chat.send': ('chat.html#send', 'chat/chat.py')},
            'chat.main': {}}}
