# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/chat.ipynb.

# %% auto #0
__all__ = ['app', 'rt', 'db', 'dialogs', 'msgs', 'state', 'js_ui', 'js_submit', 'sysp', 'models', 'MsgType', 'Dialog', 'Message',
           'AppState', 'hideButton', 'hide', 'unhide', 'edit_msg_put', 'edit_msg', 'edit_btn', 'bubble', 'ask_llm',
           'llm_rsp', 'mk_prompt', 'send', 'load_dialog', 'dlgdropdown', 'setmodel', 'modeldropdown', 'submit_btn',
           'chatpg']

# %% ../nbs/chat.ipynb #9883ceb8
from fastlucide.icons import spritesheet, Eye_off, eye, pencil

# %% ../nbs/chat.ipynb #9f5181d9
from fasthtml.common import *
from lisette import *
from fastlite import *
import random
import string
import json
from dataclasses import dataclass, field

# %% ../nbs/chat.ipynb #8a66281e
app = FastHTML(hdrs=(
        Link(href='https://cdn.jsdelivr.net/npm/daisyui@5', rel='stylesheet', type='text/css'),
        Link(href='https://cdn.jsdelivr.net/npm/daisyui@5/themes.css', rel='stylesheet', type='text/css'),
        Script(src='https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4'),
        Link(rel='stylesheet', href='https://cdn.jsdelivr.net/npm/@tailwindcss/typography/dist/typography.min.css'),
        MarkdownJS(),
        ),
    )

# %% ../nbs/chat.ipynb #0153eebc
# For convenience
rt = app.route

# %% ../nbs/chat.ipynb #fc27f08b
class MsgType(enum.StrEnum):
    note = 'Note'
    prompt = 'Prompt'
    ai = 'AI'

# %% ../nbs/chat.ipynb #eca189df
#| eval: false
db = database('solveish.db')

# %% ../nbs/chat.ipynb #19bb83af
class Dialog: id:int; uid:int; messages:str; name:str
class Message: id:int; dlgid:int; uid:int; content:str; author:str; o:int; hidden:bool

# %% ../nbs/chat.ipynb #de35a260
#| eval: false
dialogs = db.create(Dialog, transform=True)
msgs = db.create(Message, transform=True)

# %% ../nbs/chat.ipynb #25f2d745
@dataclass
class AppState:
    uid: int = 123
    h: list = field(default_factory=list)
    dlgid: int = field(default_factory=lambda: random.randint(1, 100000))
    dlgname: str = field(default_factory=lambda: ''.join(random.choices(string.ascii_lowercase, k=6)))
    model: str = 'claude-haiku-4-5'

    def randomize(self):
        self.h = []
        self.dlgid = random.randint(1, 100000)
        self.dlgname = ''.join(random.choices(string.ascii_lowercase, k=6))
        return self

    def setdlg(self, dlgid):
        dlg = dialogs[dlgid]
        h = msgs('dlgid=?', [dlg.id], order_by='o')
        self.h = [{'content': m.content, 'author': m.author} for m in h]
        self.dlgid = dlg.id
        self.dlgname = dlg.name

# %% ../nbs/chat.ipynb #7e25a543
state = AppState()

# %% ../nbs/chat.ipynb #ac317a00
js_ui = '''
document.querySelectorAll('input[name="msg_type"]').forEach(radio => {
    radio.addEventListener('change', () => {
        let input = document.getElementById('msg');
        input.placeholder = radio.value === 'note' ? 'Markdown...' : 'Ask LLM...';
        input.className = radio.value === 'note' ? 'input input-warning' : 'input input-primary';

        let button = document.getElementById('send');
        button.textContent = radio.value === 'note' ? 'Add Note' : 'Prompt LLM';
        button.className = radio.value === 'note' ? 'btn btn-warning' : 'btn btn-primary';
    });
});
'''

# %% ../nbs/chat.ipynb #56888264
js_submit = '''
document.getElementById('msg').addEventListener('keydown', (e) => {
    if ((e.shiftKey) && e.key === 'Enter') {
        e.preventDefault();
        document.getElementById('send').click()
    }
});
'''

# %% ../nbs/chat.ipynb #d34eb407
def hideButton(msg):
    icon = Eye_off() if msg.hidden else eye()
    rt = unhide if msg.hidden else hide
    return Button(icon, cls='btn btn-ghost btn-xs', hx_post=rt, hx_vals=json.dumps(dict(msgid=msg.id)), hx_swap='outerHTML')

# %% ../nbs/chat.ipynb #1c3cad42
@rt
def hide(msgid:int):
    m = msgs.update({'hidden': True}, msgid)
    return hideButton(m)

# %% ../nbs/chat.ipynb #4a9219ad
@rt
def unhide(msgid:int):
    m = msgs.update({'hidden': False}, msgid)
    return hideButton(m)

# %% ../nbs/chat.ipynb #fad720de
@rt('/edit_msg', methods='put')
def edit_msg_put(msg:str, msg_type:str, msgid:int):
    msg = msgs.update({'content': msg}, msgid)
    submit_btn = Button('Prompt LLM', id='send', hx_post=send, hx_target='#chat', hx_swap='beforeend', cls='btn btn-primary', style="padding: 1rem;",
    hx_swap_oob='true')
    return Div(msg.content, id=f'msg-{msg.id}', cls='marked prose'), submit_btn

# %% ../nbs/chat.ipynb #5efec465
@rt(methods='get')
def edit_msg(msgid:int):
    btn = Button('Save', id='send', hx_put=edit_msg_put, hx_target=f'#msg-{msgid}', cls='btn btn-primary', style="padding: 1rem;", hx_swap_oob='true', hx_vals=json.dumps({'msgid':msgid}), hx_swap='outerHTML')
    return msgs[msgid].content, btn

# %% ../nbs/chat.ipynb #c26693b2
def edit_btn(msg):
    icon = pencil()
    return Button(icon, cls='btn btn-ghost btn-xs', hx_get=edit_msg.to(msgid=msg.id), hx_target='#msg', hx_on__after_request="let ta = htmx.find('#msg'); ta.value = ta.textContent; ta.focus()")

# %% ../nbs/chat.ipynb #d7ef5ce1
def bubble(msg):
    cls = {MsgType.prompt:'bg-blue-100', MsgType.ai:'bg-base-300', MsgType.note:'bg-warning/20'}
    toolbar = Div(
        hideButton(msg),
        edit_btn(msg),
        cls='flex justify-end pt-1')
    return Div(
        Div(Div(msg.content, id=f'msg-{msg.id}', cls='marked prose'), cls=f'rounded-xl p-4 {cls[msg.author]}'
            ),
        toolbar,
        cls='max-w-3xl mx-auto w-full'
    )

# %% ../nbs/chat.ipynb #b6623174
sysp = "You are a chat model, in a chat with a user. Given the chat history as context, answer the user's current question concisely."

# %% ../nbs/chat.ipynb #1de6a901
@rt
def ask_llm(msg:str):
    ctx = get_ctx(state.dlgid)
    r = Chat(model=state.model, sp=sysp)(mk_prompt(msg, ctx))
    rsp = r.choices[0].message.content
    #update_h(msg, MsgType.prompt)
    m = update_h(rsp, MsgType.ai)
    return bubble(m)

# %% ../nbs/chat.ipynb #3b580ed4
def llm_rsp(msg):
    return Div(
        Span(cls='loading loading-ring loading-md'), cls='flex justify-center',
        hx_post=ask_llm, hx_trigger='load', hx_swap='outerHTML',
        hx_vals=f'{{"msg": "{msg}"}}'
        )

# %% ../nbs/chat.ipynb #59f2d3da
def mk_prompt(msg, h):
    return "Past messages: " + json.dumps(h) + "\n\nCurrent question: " + msg

# %% ../nbs/chat.ipynb #436891ec
@rt
def send(msg: str, msg_type:str):
    msg_type = MsgType[msg_type]
    if msg_type == MsgType.note:
        return bubble(update_h(msg, msg_type))
    else:
        return (bubble(update_h(msg, msg_type)), llm_rsp(msg))

# %% ../nbs/chat.ipynb #6f450521
@rt
def load_dialog(dlgid:int):
    #TODO: FIX
    state.setdlg(dlgid)
    h = msgs('dlgid=?', [state.dlgid], order_by='o')
    return (bubble(m) for m in h)

# %% ../nbs/chat.ipynb #1b62f251
def dlgdropdown():
    udlgs = dialogs('uid=?', [123])

    return Details(cls='dropdown dropdown-top')(
        Summary('Dialogues', cls='btn m-1'),
        Ul(cls='menu dropdown-content bg-base-100 rounded-box z-1 w-52 p-2 shadow-sm')(
            (Li(A(dlg.name, hx_post=load_dialog.to(dlgid=dlg.id), hx_target='#chat', hx_swap='innerHTML')) for dlg in udlgs)
        )
    )

# %% ../nbs/chat.ipynb #9f4b983a
models = ['claude-haiku-4-5', 'claude-opus-4-5', 'claude-sonnet-4-5']
models

# %% ../nbs/chat.ipynb #d9cd2519
@rt
def setmodel(name:str):
    state.model = name
    return Summary(state.model, cls='btn m-1', id="selmodel")

# %% ../nbs/chat.ipynb #017cb105
def modeldropdown():
    return Details(cls='dropdown dropdown-top')(
        Summary(state.model, cls='btn m-1', id="selmodel"),
        Ul(cls='menu dropdown-content bg-base-100 rounded-box z-1 w-52 p-2 shadow-sm')(
            (Li(A(m, hx_post=setmodel.to(name=m), hx_target='#selmodel', hx_swap="outerHTML", hx_on_click="this.closest('details').removeAttribute('open')")) for m in models)
        )
    )

# %% ../nbs/chat.ipynb #76b89a1c
def submit_btn():
    return Button('Prompt LLM', id='send', hx_post=send, hx_target='#chat', hx_swap='beforeend', cls='btn btn-primary', style="padding: 1rem;")

# %% ../nbs/chat.ipynb #d06fbd33
@rt
def chatpg():
    state.randomize()
    return Div(
        Div(id='chat', style='width:100%; box-sizing:border-box; padding:0 1rem; border: 1px solid #ccc; border-radius: 0.5rem; min-height:400px; height: calc(100vh - 158px); overflow-y: auto;')(
        ),
        
        Form(
            Div(
                Label(Input(type='radio', name='msg_type', value='prompt', checked='checked', cls='radio radio-primary'), 'Prompt', style="padding: 1rem;"),
                Label(Input(type='radio', name='msg_type', value='note', cls='radio radio-secondary'), 'Note', style="padding: 1rem;"),
                submit_btn(),
                modeldropdown(),
                dlgdropdown(),
                style="padding: 1rem; display:flex; justify-content:center; align-items:center"
            ),
            Textarea(id='msg', type='text', placeholder='Type something...', style='width: 100%;', cls='input input-primary'),
            hx_on__after_request="if(event.detail.successful) htmx.find('#msg').value=''",
            style='position: fixed; bottom: 0; width: 100%; padding:1rem'
        ),
        Script(js_ui),
        Script(js_submit),
        style='width: 100%'
    ), spritesheet
