# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/core.ipynb.

# %% auto #0
__all__ = ['app', 'rt', 'sysp', 'h', 'js_ui', 'js_submit', 'MsgType', 'bubble', 'mk_prompt', 'ask_llm', 'llm_rsp', 'send']

# %% ../nbs/core.ipynb #b237d6f7
from fasthtml.common import *
from lisette import *

# %% ../nbs/core.ipynb #8a66281e
app = FastHTML(hdrs=(
        Link(href='https://cdn.jsdelivr.net/npm/daisyui@5', rel='stylesheet', type='text/css'),
        Link(href='https://cdn.jsdelivr.net/npm/daisyui@5/themes.css', rel='stylesheet', type='text/css'),
        Script(src='https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4'),
        Link(rel='stylesheet', href='https://cdn.jsdelivr.net/npm/@tailwindcss/typography/dist/typography.min.css'),
        MarkdownJS(),
        ),
    )

# %% ../nbs/core.ipynb #0153eebc
# For convenience
rt = app.route

# %% ../nbs/core.ipynb #428afcaa
sysp = "You are a chat model, in a chat with a user. Given the chat history as context, answer the user's current question concisely."

# %% ../nbs/core.ipynb #3f5d2dd7
class MsgType(enum.StrEnum):
    note = 'Note'
    prompt = 'Prompt'
    ai = 'AI'

# %% ../nbs/core.ipynb #a2edb8ec
def bubble(msg:str, msg_type:MsgType=MsgType.prompt):
    if msg_type == MsgType.ai:
        return Div(Div(msg, cls='chat-bubble chat-bubble-secondary marked prose'), cls='chat chat-end')
    elif msg_type == MsgType.prompt:
        return Div(Div(msg, cls='chat-bubble chat-bubble-primary'), cls='chat chat-start')
    else:
        return Div(Div(msg, cls='chat-bubble chat-bubble-warning marked prose'), cls='chat chat-start')

# %% ../nbs/core.ipynb #464f0850
def mk_prompt(msg, h):
    return "Past context/conversation: " + "\n".join(h) + "\n\nCurrent question: " + msg

# %% ../nbs/core.ipynb #31f052b0
# We need a way to store the history of the conversation.
h = []

# %% ../nbs/core.ipynb #f3270501
@rt
def ask_llm(msg:str):
    global h
    r = Chat(model='claude-haiku-4-5', sp=sysp)(mk_prompt(msg, h))
    rsp = r.choices[0].message.content
    h += [f'user: {msg}, llm: {rsp}']
    return bubble(rsp, MsgType.ai)

# %% ../nbs/core.ipynb #59ce56ee
def llm_rsp(msg):
    return Div(
        Span(cls='loading loading-ring loading-md'), cls='flex justify-center',
        hx_post=ask_llm, hx_trigger='load', hx_swap='outerHTML',
        hx_vals=f'{{"msg": "{msg}"}}'
        )

# %% ../nbs/core.ipynb #0b6592c1
@rt
def send(msg: str, msg_type:str):
    msg_type = MsgType[msg_type]
    if msg_type == MsgType.note:
        global h
        h += [f'user_note: {msg}']
        return bubble(msg, msg_type)
    else:
        return (bubble(msg, msg_type), llm_rsp(msg))

# %% ../nbs/core.ipynb #1f59cba6
js_ui = '''
document.querySelectorAll('input[name="msg_type"]').forEach(radio => {
    radio.addEventListener('change', () => {
        let input = document.getElementById('msg');
        input.placeholder = radio.value === 'note' ? 'Markdown...' : 'Ask LLM...';
        input.className = radio.value === 'note' ? 'input input-warning' : 'input input-primary';

        let button = document.getElementById('send');
        button.textContent = radio.value === 'note' ? 'Add Note' : 'Prompt LLM';
        button.className = radio.value === 'note' ? 'btn btn-warning' : 'btn btn-primary';
    });
});
'''

# %% ../nbs/core.ipynb #cfcb5d76
js_submit = '''
document.getElementById('msg').addEventListener('keydown', (e) => {
    if ((e.shiftKey) && e.key === 'Enter') {
        e.preventDefault();
        document.getElementById('send').click()
    }
});
'''
