# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/main.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/main.ipynb #d93c3b70
from .chat import app
from fasthtml.common import serve

# %% ../nbs/main.ipynb #9e48b0e8
#| eval: false
if __name__ == '__main__':
    serve(appname='chat.main')
