# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/run.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/run.ipynb #d93c3b70
from .chat import app
from fasthtml.common import serve

# %% ../nbs/run.ipynb #9e48b0e8
#| eval: false
serve()
